// This file controls the target URLs matched from the "sendto" query parameter.
// Add or update the available target URLs by saving edits to these values:

const redirects = {
  main: "https://www.facebook.com/Wildcat-Bluff-Disc-Golf-Course-392191570823455/posts",
  hole1blue: "",
  hole1red: "",
  hole2blue: "",
  hole2red: "",
  hole3: "",
  hole4blue: "",
  hole4red: "",
  hole5blue: "",
  hole5red: "",
  hole6blue: "",
  hole6red: "",
  hole7: "",
  hole8: "",
  hole9: "",
  hole10blue: "",
  hole10red: "",
  hole11blue: "",
  hole11red: "",
  hole12blue: "",
  hole12red: "",
  hole13blue: "https://youtu.be/zMVDIwlVzn4",
  hole13red: "",
  hole14blue: "https://youtu.be/-bB5DtfbFY8",
  hole14red: "",
  hole15: "https://youtu.be/NwDC1rUvrnk",
  hole16: "https://youtu.be/M4Q46L3t6cc",
  hole17blue: "https://youtu.be/q8Z2FWjI5Wk",
  hole17red: "",
  hole18blue: "",
  hole18red: "https://youtu.be/m7KwsJtpnP4",
  hole19: "https://youtu.be/jlFLqIyBxlM",
  hole20blue: "",
  hole20red: "https://youtu.be/jIc3xAtrSR4",
  hole21: "https://youtu.be/62iBfy52aT4"
};
