// This file controls the target URLs matched from the "sendto" query parameter.
// Add or update the available target URLs by saving edits to these values:

const redirects = {
  main: "https://www.facebook.com/Wildcat-Bluff-Disc-Golf-Course-392191570823455/posts",
  hole1long: "",
  hole1short: "",
  hole2long: "",
  hole2short: "",
  hole3: "",
  hole4long: "",
  hole4short: "",
  hole5long: "",
  hole5short: "",
  hole6long: "",
  hole6short: "",
  hole7: "",
  hole8: "",
  hole9: "",
  hole10long: "",
  hole10short: "",
  hole11long: "",
  hole11short: "",
  hole12long: "",
  hole12short: "",
  hole13long: "https://youtu.be/zMVDIwlVzn4",
  hole13short: "",
  hole14long: "https://youtu.be/-bB5DtfbFY8",
  hole14short: "",
  hole15: "https://youtu.be/NwDC1rUvrnk",
  hole16: "https://youtu.be/M4Q46L3t6cc",
  hole17long: "",
  hole17short: "",
  hole18long: "",
  hole18short: "https://youtu.be/m7KwsJtpnP4",
  hole19: "https://youtu.be/jlFLqIyBxlM",
  hole20long: "",
  hole20short: "https://youtu.be/jIc3xAtrSR4",
  hole21: "https://youtu.be/62iBfy52aT4"
};
